/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-10-21 10:20:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Date;
import main.MemberDto;
import portfolio.ConfigDTO;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/main/./footer.jsp", Long.valueOf(1697181196000L));
    _jspx_dependants.put("jar:file:/D:/portfolio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portfolio/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/main/./typeInfo.jsp", Long.valueOf(1697774116000L));
    _jspx_dependants.put("/main/./main.jsp", Long.valueOf(1697181266000L));
    _jspx_dependants.put("jar:file:/D:/portfolio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portfolio/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696946006000L));
    _jspx_dependants.put("/main/./header.jsp", Long.valueOf(1697734664000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("portfolio.ConfigDTO");
    _jspx_imports_classes.add("main.MemberDto");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String nm = (String)session.getAttribute("name");
Date maindate = new Date();
DateFormat mdf = new SimpleDateFormat("yyyyMMddhms");
String mdates = mdf.format(maindate);

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:title\" content=\"인천검단 레미안\">\r\n");
      out.write("<title>인천검단 레미안</title>\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/normalize.css?v=");
      out.print(mdates);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/slick.css?v=");
      out.print(mdates);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/swiper.min.css?v=");
      out.print(mdates);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css?v=");
      out.print(mdates);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/cal-style.css?v=");
      out.print(mdates);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/common.css?v=");
      out.print(mdates);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./dadmin/css/sweetalert.min.css?v=");
      out.print(mdates);
      out.write("\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/top.css?v=");
      out.print(mdates);
      out.write("\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- wrap -->\r\n");
      out.write("<div id=\"mask\"></div>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("	<!-- header 로고 * 대메뉴,소메뉴-->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");

Date hddt = new Date();
DateFormat hddf = new SimpleDateFormat("yyyyMMddhms");
String hddts = hddf.format(hddt);


MemberDto mdto = (MemberDto)session.getAttribute("mdto");
String name = "";
if(mdto != null){
	name = (String)mdto.getMname();
}

      out.write("    \r\n");
      out.write("<!-- header 로고 * 대메뉴,소메뉴-->\r\n");
      out.write("	<header id=\"hd\">\r\n");
      out.write("		<div class=\"top_menu\">\r\n");
      out.write("	        <ul class=\"top_menu_list\">\r\n");
      out.write("	        ");

	        if(name != null && !name.isEmpty()){
	        
      out.write("\r\n");
      out.write("	        	<li>");
      out.print(name );
      out.write("님 환영합니다 <a href=\"./userlogOut.do\">[로그아웃]</a></li>\r\n");
      out.write("	        	<li><a href=\"./faq.do\">FAQ</a></li>\r\n");
      out.write("		        <li><a href=\"./notice.do\">공지사항</a></li>\r\n");
      out.write("	        ");

	        }
	        else{
        	
      out.write("\r\n");
      out.write("	        	<li><a href=\"./login.jsp\">로그인</a></li>\r\n");
      out.write("		        <li><a href=\"./join_agree.jsp\">회원가입</a></li>\r\n");
      out.write("		        <li><a href=\"./faq.do\">FAQ</a></li>\r\n");
      out.write("		        <li><a href=\"./notice.do\">공지사항</a></li>\r\n");
      out.write("	        ");

	        }
	        
      out.write("        		        \r\n");
      out.write("		    </ul>\r\n");
      out.write("    	</div>\r\n");
      out.write("	\r\n");
      out.write("        <div class=\"top\">\r\n");
      out.write("            <h1><a href=\"./mainPage.do\" class=\"icon-hd-logo\"></a></h1>\r\n");
      out.write("            <nav id=\"gnb\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\"><span>사업정보</span></a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"./sub01.jsp\">지구안내</a></li>\r\n");
      out.write("                        <li><a href=\"./sub02.jsp\">입지안내</a></li>\r\n");
      out.write("                        <li><a href=\"\">지역조감도</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\"><span>단지정보</span></a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"./sub03.jsp\">단지안내</a></li>\r\n");
      out.write("                        <li><a href=\"\">시스템</a></li>\r\n");
      out.write("                        <li><a href=\"\">단지배치도</a></li>\r\n");
      out.write("                        <li><a href=\"\">동호배치도</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\"><span>세대정보</span></a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"\">타입별 평면도</a></li>\r\n");
      out.write("                        <li><a href=\"\">인테리어</a></li>\r\n");
      out.write("						<li><a href=\"\">사이버모델하우스</a></li>\r\n");
      out.write("						<li><a href=\"\">인테리어마감재</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\"><span>공급정보</span></a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                       <li><a href=\"\">입주자 모집공고</a></li>\r\n");
      out.write("                        <li><a href=\"\">E-카달로그</a></li>\r\n");
      out.write("                         <li><a href=\"\">공급일정 안내</a></li>\r\n");
      out.write("                        <li><a href=\"\">오시는 길</a></li>\r\n");
      out.write("                      <li><a href=\"\"></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a><span>사전방문예약</span></a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"\" id=\"reserveA\">사전방문예약</a></li>\r\n");
      out.write("                        <li><a href=\"\" id=\"reserveCK\">사전방문예약확인</a></li>\r\n");
      out.write("                        <li><a href=\"\" id=\"reserveCancel\">사전방문예약취소</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- header 로고 * 대메뉴,소메뉴 END-->\r\n");
      out.write("<script>\r\n");
      out.write("/* 예약 페이지 가기 */\r\n");
      out.write("function go_reserve(){\r\n");
      out.write("	if(\"");
      out.print(name);
      out.write("\" != null && '");
      out.print(name);
      out.write("'.trim() != \"\"){\r\n");
      out.write("		location.href=\"./reservation_in.do\"\r\n");
      out.write("	}\r\n");
      out.write("	else{\r\n");
      out.write("		alert(\"사전방문 예약은 로그인 후 가능합니다.\");\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"reserveA\").addEventListener(\"click\",function(event){\r\n");
      out.write("	go_reserve();\r\n");
      out.write("	event.preventDefault();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 예약 확인 가기 */\r\n");
      out.write("function go_reserveCk(){\r\n");
      out.write("	if(\"");
      out.print(name);
      out.write("\" != null && '");
      out.print(name);
      out.write("'.trim() != \"\"){\r\n");
      out.write("		location.href=\"./reservation_ck.do\"\r\n");
      out.write("	}\r\n");
      out.write("	else{\r\n");
      out.write("		alert(\"예약확인은 로그인 후 가능합니다.\");\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"reserveCK\").addEventListener(\"click\",function(event){\r\n");
      out.write("	go_reserveCk();\r\n");
      out.write("	event.preventDefault();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/*취소 화면 가기*/\r\n");
      out.write("function go_reserveCancel(){\r\n");
      out.write("	if(\"");
      out.print(name);
      out.write("\" != null && '");
      out.print(name);
      out.write("'.trim() != \"\"){\r\n");
      out.write("		location.href=\"./reservation_cancel.do\"\r\n");
      out.write("	}\r\n");
      out.write("	else{\r\n");
      out.write("		alert(\"예약취소 기능은 로그인 후 사용 가능합니다.\");\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("document.getElementById(\"reserveCancel\").addEventListener(\"click\",function(event){\r\n");
      out.write("	go_reserveCancel();\r\n");
      out.write("	event.preventDefault();\r\n");
      out.write("});\r\n");
      out.write("</script>	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<!-- header 로고 * 대메뉴,소메뉴 END-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"index\">\r\n");
      out.write("	<!-- 메인 화면 시작 -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- 메인 화면 시작 -->\r\n");
      out.write("	<section id=\"px0\" class=\"px-sect\">\r\n");
      out.write("		<ul class=\"main-slider\">\r\n");
      out.write("		    <li class=\"i1 px-h\">\r\n");
      out.write("               <div class=\"tb-areaset\">\r\n");
      out.write("                   <div class=\"tb-type animated fadeInUp\">\r\n");
      out.write("                       <div class=\"text-center\">\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </div>\r\n");
      out.write("		    </li>\r\n");
      out.write("		    <li class=\"i2 px-h\">\r\n");
      out.write("               <div class=\"tb-areaset\">\r\n");
      out.write("                   <div class=\"tb-type\">\r\n");
      out.write("                       <div class=\"text-center\">\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </div>\r\n");
      out.write("		    </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("        <div class=\"txt-ref\">※ 상기 이미지는 소비자의 이해를 돕기 위한 것으로 실제와 다를 수 있습니다.</div>\r\n");
      out.write("        <div class=\"slider-progress\">\r\n");
      out.write("           <div class=\"progress\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"scroll-info\">\r\n");
      out.write("            <span class=\"ico-mouse\"><em class=\"animated scrollBall infinite\"></em></span> <span>Scroll-Down</span>\r\n");
      out.write("        </div>\r\n");
      out.write("		<div class=\"index-nv\">\r\n");
      out.write("            <ol>\r\n");
      out.write("                <li class=\"on\"><a href=\"#px0\" onClick=\"scrollMove('#px0');return false;\"></a></li>\r\n");
      out.write("                <li><a href=\"#px1\" onClick=\"scrollMove('#px1');return false;\"></a></li>\r\n");
      out.write("                <li><a href=\"#px2\" onClick=\"scrollMove('#px2');return false;\"></a></li>\r\n");
      out.write("                <li class=\"\"><a href=\"#px3\" onClick=\"scrollMove('#px3');return false;\"></a></li>\r\n");
      out.write("                <li><a href=\"#px4\" onClick=\"scrollMove('#px4');return false;\"></a></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"sect-info px-sect\">\r\n");
      out.write("	    <div class=\"w-base\">\r\n");
      out.write("			 <h3 class=\"animated fadeInUp mt10\"><small>\r\n");
      out.write("					<span class=\"fc-orange\">검</span>증된 신도시 <br>\r\n");
      out.write("		            <span class=\"fc-orange\">단</span>번에 누려라\r\n");
      out.write("			 </small></h3>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</section>\r\n");
      out.write("<section id=\"px1\" class=\"sect01 px-sect\">\r\n");
      out.write("        <div class=\"w-base\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6 col-xs-12 pa20-xs pt0-xs mt30-xs\">\r\n");
      out.write("                    <span class=\"img-group\">\r\n");
      out.write("                        <span>\r\n");
      out.write("                            <em class=\"animated zoomIn\"><img src=\"img/ms01.png\" class=\"img-responsive center-block\" alt=\"\"></em>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-xs-12 pl50 pa30-xs pb0-xs\">\r\n");
      out.write("                    <h3 class=\"fw300 animated fadeInUp\">\r\n");
      out.write("                        <small>인천1호선 연장, 법조타운 조성, 특화산업 클러스터까지 <br class=\"mobile\"></small>더 나은 내일로 힘차게 도약하는 <br > <span class=\"fc-orange\">인천 검단신도시</span>\r\n");
      out.write("                    </h3>\r\n");
      out.write("                    <div class=\"animated fadeInUp\">\r\n");
      out.write("                    <ul class=\"lst-dot pt20 pt0-xs\">\r\n");
      out.write("                        <li>인천1호선 연장으로완성되는 역세권</li>\r\n");
      out.write("                        <li>법원과 검찰청 신설로완성되는 법조타운</li>\r\n");
      out.write("                        <li>특화산업 클러스터 조성으로완성되는 직주근접</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   <a href=\"\" class=\"btn-basic mt50 animated fadeInUp\">자세히보기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("	</section>\r\n");
      out.write("    <section id=\"px3\" class=\"sect03 px-sect\">\r\n");
      out.write("        <div class=\"\"> \r\n");
      out.write("            <h3 class=\"ff-play animated fadeInUp fc-wh\">인천검단 <b>AA13-1 BL</b></h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6 col-xs-12 life-slider-area\">\r\n");
      out.write("                    <ul class=\"life-slider animated fadeInUp\">\r\n");
      out.write("                       <li>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <img src=\"img/main_life01.jpg\" class=\"img-responsive center-block\" alt=\"\">\r\n");
      out.write("                                    <i class=\"cover\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"s-info\">\r\n");
      out.write("                                    <em class=\"num animated fadeInUp\">01</em>\r\n");
      out.write("                                    <h4 class=\"animated fadeInUp\">더 빠른 교통</h4>\r\n");
      out.write("                                    <p class=\"animated fadeInUp\">\r\n");
      out.write("            + 인천1호선 검단 연장(예정)으로 더욱 개선되는 대중교통 접근성 <br>\r\n");
      out.write("			+ 수도권제2순환고속도로, 인천국제공항고속도로 등 우수한 광역교통망\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <img src=\"img/main_life02.jpg\" class=\"img-responsive center-block\" alt=\"\">\r\n");
      out.write("                                    <i class=\"cover\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"s-info\">\r\n");
      out.write("                                    <em class=\"num animated fadeInUp\">02</em>\r\n");
      out.write("                                    <h4 class=\"animated fadeInUp\">더 편한 생활</h4>\r\n");
      out.write("                                    <p class=\"animated fadeInUp\">\r\n");
      out.write("            + 인근에 복합문화상업지구 넥스트 콤플렉스 조성 예정으로 기대되는 생활 편의성 <br/>\r\n");
      out.write("			+ 단지 옆 초등학교, 주변에 중·고교 신설 예정, 영어마을도 인접한 명문교육환경\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("						 <li>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <img src=\"img/main_life01.jpg\" class=\"img-responsive center-block\" alt=\"\">\r\n");
      out.write("                                    <i class=\"cover\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"s-info\">\r\n");
      out.write("                                    <em class=\"num animated fadeInUp\">01</em>\r\n");
      out.write("                                    <h4 class=\"animated fadeInUp\">더 빠른 교통</h4>\r\n");
      out.write("                                    <p class=\"animated fadeInUp\">\r\n");
      out.write("            + 인천1호선 검단 연장(예정)으로 더욱 개선되는 대중교통 접근성 <br>\r\n");
      out.write("			+ 수도권제2순환고속도로, 인천국제공항고속도로 등 우수한 광역교통망\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <img src=\"img/main_life02.jpg\" class=\"img-responsive center-block\" alt=\"\">\r\n");
      out.write("                                    <i class=\"cover\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"s-info\">\r\n");
      out.write("                                    <em class=\"num animated fadeInUp\">02</em>\r\n");
      out.write("                                    <h4 class=\"animated fadeInUp\">더 편한 생활</h4>\r\n");
      out.write("                                    <p class=\"animated fadeInUp\">\r\n");
      out.write("            + 인근에 복합문화상업지구 넥스트 콤플렉스 조성 예정으로 기대되는 생활 편의성 <br/>\r\n");
      out.write("			+ 단지 옆 초등학교, 주변에 중·고교 신설 예정, 영어마을도 인접한 명문교육환경\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-xs-12 pull-right life-inven-area animated fadeInUp\">\r\n");
      out.write("                    <ul class=\"life-slider-inven\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <img src=\"img/main_life01.jpg\" class=\"img-responsive center-block\" alt=\"\">\r\n");
      out.write("                                    <i class=\"cover\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"s-info\">\r\n");
      out.write("                                    <h4>더 빠른 교통</h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <img src=\"img/main_life02.jpg\" class=\"img-responsive center-block\" alt=\"\">\r\n");
      out.write("                                    <i class=\"cover\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"s-info\">\r\n");
      out.write("                                    <h4>더 편한 생활</h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("						<li>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <img src=\"img/main_life01.jpg\" class=\"img-responsive center-block\" alt=\"\">\r\n");
      out.write("                                    <i class=\"cover\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"s-info\">\r\n");
      out.write("                                    <h4>더 빠른 교통</h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <img src=\"img/main_life02.jpg\" class=\"img-responsive center-block\" alt=\"\">\r\n");
      out.write("                                    <i class=\"cover\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"s-info\">\r\n");
      out.write("                                    <h4>더 편한 생활</h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 메인 화면 종료 -->");
      out.write("\r\n");
      out.write("    <!-- 메인 화면 종료 -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- 타입정보 시작-->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("<!-- 타입정보 시작-->\r\n");
      out.write("	<section id=\"px4\" class=\"sect04 px-sect last-sect\">\r\n");
      out.write("        <div class=\"w-base\">\r\n");
      out.write("            <div class=\"tit-area  animated fadeInUp m_center\">\r\n");
      out.write("                <h3>편안하고 실용적인 <br class=\"m_br\">합리적 공간배치<br class=\"m_br\"><a href=\"#\">more</a></h3>\r\n");
      out.write("                <p class=\"animated fadeInUp m_center\">더 나은 삶, 나은 내일<br>가족의 행복한 이야기로 가득 채워집니다</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("             <div class=\"contents-4-box row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <ul class=\"nav nav-tabs box-nav m_flex_center\">\r\n");
      out.write("                        <!-- 타입 출력 -->\r\n");
      out.write("                        ");
      if (_jspx_meth_app_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        <!-- 타입 출력 끝-->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-12 col-xs-12\">\r\n");
      out.write("                    <div class=\"iso-box\">\r\n");
      out.write("                    ");
      if (_jspx_meth_app_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--// 타입정보 끝-->");
      out.write("\r\n");
      out.write("	<!--// 타입정보 끝-->\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("  <!-- 카피라이터 -->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!-- 카피라이터 -->\r\n");
      out.write("	  	<footer id=\"ft\">\r\n");
      out.write("  	    <div>\r\n");
      out.write("              <div class=\"ft-area\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-sm-9 col-xs-12 pull-right\"><!--col-sm-10-->\r\n");
      out.write("                          <div class=\"row\">\r\n");
      out.write("                              <div class=\"col-sm-12 col-xs-12\">\r\n");
      out.write("                                  <p class=\"tit\">인천검단 레미안 주택전시관</p>\r\n");
      out.write("                                  <p class=\"copy\">\r\n");
      out.write("                                    <em>위치</em><span>인천 서구 청라동 22-2</span> <br class=\"m_br\">   \r\n");
      out.write("									&nbsp;<em> LH콜센터</em><span>1688-0123</span>\r\n");
      out.write("                                    <em>주택전시관</em><span>000-123-5678</span>\r\n");
      out.write("                                  </p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p class=\"copyright-p\">\r\n");
      out.write("                      <img src=\"img/logo_ft.png\" class=\"img-responsive center-block\" alt=\"\">\r\n");
      out.write("                  </p>\r\n");
      out.write("                  <div class=\"right-line px-h\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("  	    </div>\r\n");
      out.write("  	</footer>	<!-- // footer -->\r\n");
      out.write("  <!-- 카피라이터 끝 --></html>");
      out.write("\r\n");
      out.write("  <!-- 카피라이터 끝 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //container -->\r\n");
      out.write("<!-- //wrap -->\r\n");
      out.write("<script src=\"js/slick.min.js?v=");
      out.print(mdates);
      out.write("\"></script>\r\n");
      out.write("<script src=\"js/common.js?v=");
      out.print(mdates);
      out.write("\"></script>\r\n");
      out.write("<script src=\"js/swiper.min.js?v=");
      out.print(mdates);
      out.write("\"></script>\r\n");
      out.write("<script src=\"js/layout.js?v=");
      out.print(mdates);
      out.write("\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(\".tab_showroom\").on(\"click\", function () {\r\n");
      out.write("        var num = $(this).data(\"num\");\r\n");
      out.write("        $(\".tab_showroom\").removeClass(\"active\");\r\n");
      out.write("        $(this).addClass(\"active\");\r\n");
      out.write("        $(\".showroom\").hide();\r\n");
      out.write("        $(\"#showroom_\" + num).show();\r\n");
      out.write("        $(\".showroom_slide\").hide();\r\n");
      out.write("        $(\"#showroom_slide_\" + num).show();\r\n");
      out.write("\r\n");
      out.write("        if( !$('#showroom_slide_' + num + ' .swiper-container').hasClass(\"swiper-container-initialized\") ) {\r\n");
      out.write("            swiper = new Swiper('#showroom_slide_' + num + ' .swiper-container', {\r\n");
      out.write("                slidesPerView: 1,\r\n");
      out.write("                loop: true,\r\n");
      out.write("                navigation: {\r\n");
      out.write("                    nextEl: '.sub-slider__next',\r\n");
      out.write("                    prevEl: '.sub-slider__prev',\r\n");
      out.write("                },\r\n");
      out.write("                pagination: {\r\n");
      out.write("                    el: '.swiper-pagination',\r\n");
      out.write("                    clickable: true,\r\n");
      out.write("                    renderBullet: function (index, className) {\r\n");
      out.write("                        return '<span class=\"' + className + '\"></span>';\r\n");
      out.write("                    },\r\n");
      out.write("                },\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            setTimeout(reInit,500);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    if( !$('#showroom_slide_1 .swiper-container').hasClass(\"swiper-container-initialized\") ){\r\n");
      out.write("        swiper = new Swiper('#showroom_slide_1 .swiper-container', {\r\n");
      out.write("            slidesPerView: 1,\r\n");
      out.write("            loop: true,\r\n");
      out.write("            navigation: {\r\n");
      out.write("                nextEl: '.sub-slider__next',\r\n");
      out.write("                prevEl: '.sub-slider__prev',\r\n");
      out.write("            },\r\n");
      out.write("            pagination: {\r\n");
      out.write("                el: '.swiper-pagination',\r\n");
      out.write("                clickable: true,\r\n");
      out.write("                renderBullet: function (index, className) {\r\n");
      out.write("                    return '<span class=\"' + className + '\"></span>';\r\n");
      out.write("                },\r\n");
      out.write("            },\r\n");
      out.write("        });\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    var dotArea = $('.main-slider .slick-dots');\r\n");
      out.write("    dotArea.wrap('<div class=\"w-base dot-control\"></div>');\r\n");
      out.write("    $(\"<em>0</em>\").prependTo('.main-slider .slick-dots>li>button');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     $('.life-slider').slick({\r\n");
      out.write("        slidesToShow: 1,\r\n");
      out.write("        slidesToScroll: 1,\r\n");
      out.write("         autoplay: true,\r\n");
      out.write("        autoplaySpeed: 3000,\r\n");
      out.write("        arrows: true,\r\n");
      out.write("        fade: true,\r\n");
      out.write("        asNavFor: '.life-slider-inven'\r\n");
      out.write("    });\r\n");
      out.write("    var dotArea = $('.life-slider .slick-arrow');\r\n");
      out.write("    dotArea.wrap('<div class=\"w-base dot-control\"></div>');\r\n");
      out.write("    $(\"<em>0</em>\").prependTo('.main-slider .slick-dots>li>button');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $('.life-slider-inven').slick({\r\n");
      out.write("        slidesToShow: 2,\r\n");
      out.write("        slidesToScroll: 1,\r\n");
      out.write("        asNavFor: '.life-slider',\r\n");
      out.write("        //centerMode: true,\r\n");
      out.write("        dots: false,\r\n");
      out.write("        arrows: false,\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.area-interior').slick({\r\n");
      out.write("        dots:true,\r\n");
      out.write("        infinite:true,\r\n");
      out.write("        autoplay:true,\r\n");
      out.write("        autoplaySpeed:3000\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("  var time = 2;\r\n");
      out.write("  var $bar,\r\n");
      out.write("    $slick,\r\n");
      out.write("    isPause,\r\n");
      out.write("    tick,\r\n");
      out.write("    percentTime;\r\n");
      out.write("\r\n");
      out.write("  $slick = $('.main-slider');\r\n");
      out.write("  $slick.slick({\r\n");
      out.write("    arrows: true,\r\n");
      out.write("    speed: 1200,\r\n");
      out.write("    dots:false,\r\n");
      out.write("    arrows:true,\r\n");
      out.write("    fade: true,\r\n");
      out.write("    infinite: true,\r\n");
      out.write("    adaptiveHeight: false\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  $bar = $('.slider-progress .progress');\r\n");
      out.write("\r\n");
      out.write("  function startProgressbar() {\r\n");
      out.write("    resetProgressbar();\r\n");
      out.write("    percentTime = 0;\r\n");
      out.write("    isPause = false;\r\n");
      out.write("    tick = setInterval(interval, 30);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function interval() {\r\n");
      out.write("    if (isPause === false) {\r\n");
      out.write("      percentTime += 1 / (time + 0.1);\r\n");
      out.write("      $bar.css({\r\n");
      out.write("        width: percentTime + \"%\"\r\n");
      out.write("      });\r\n");
      out.write("      if (percentTime >= 100) {\r\n");
      out.write("        $slick.slick('slickNext');\r\n");
      out.write("        startProgressbar();\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function resetProgressbar() {\r\n");
      out.write("    $bar.css({\r\n");
      out.write("      width: 0 + '%'\r\n");
      out.write("    });\r\n");
      out.write("    clearTimeout(tick);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  startProgressbar();\r\n");
      out.write("\r\n");
      out.write("  $('.slick-next, .slick-prev').click(function() {\r\n");
      out.write("    startProgressbar();\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_app_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_app_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_app_005fforEach_005f0_reused = false;
    try {
      _jspx_th_app_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_app_005fforEach_005f0.setParent(null);
      // /main/./typeInfo.jsp(20,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f0.setVar("type");
      // /main/./typeInfo.jsp(20,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/main/./typeInfo.jsp(20,24) '${lists}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${lists}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /main/./typeInfo.jsp(20,24) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f0.setVarStatus("list");
      int[] _jspx_push_body_count_app_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_app_005fforEach_005f0 = _jspx_th_app_005fforEach_005f0.doStartTag();
        if (_jspx_eval_app_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                        <li>\r\n");
            out.write("                            <button type=\"button\" class=\"tab_showroom ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.first ? 'active' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-num=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.index+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type.atype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</button>\r\n");
            out.write("                        </li>\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_app_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_app_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_app_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_app_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_app_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_app_005fforEach_005f0);
      _jspx_th_app_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_app_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_app_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_app_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_app_005fforEach_005f1_reused = false;
    try {
      _jspx_th_app_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_app_005fforEach_005f1.setParent(null);
      // /main/./typeInfo.jsp(30,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f1.setVar("type");
      // /main/./typeInfo.jsp(30,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/main/./typeInfo.jsp(30,20) '${lists}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${lists}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /main/./typeInfo.jsp(30,20) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f1.setVarStatus("list");
      int[] _jspx_push_body_count_app_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_app_005fforEach_005f1 = _jspx_th_app_005fforEach_005f1.doStartTag();
        if (_jspx_eval_app_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                        <div class=\"showroom\" id=\"showroom_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.index+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                            <span><img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type.aimgUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"img-responsive center-block\" alt=\"\"></span>\r\n");
            out.write("\r\n");
            out.write("                            <div class=\"area-info col-sm-1\">\r\n");
            out.write("                                <h4>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type.atype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4>\r\n");
            out.write("                                <ul>\r\n");
            out.write("                                    <li>\r\n");
            out.write("                                        <h5>주거전용</h5>\r\n");
            out.write("                                        <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type.aprivate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("㎡</p>\r\n");
            out.write("                                    </li>\r\n");
            out.write("                                    <li>\r\n");
            out.write("                                        <h5>주거공용</h5>\r\n");
            out.write("                                        <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type.apublic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("㎡</p>\r\n");
            out.write("                                    </li>\r\n");
            out.write("                                    <li>\r\n");
            out.write("                                        <h5>기타공용</h5>\r\n");
            out.write("                                        <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type.aetcpublic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("㎡</p>\r\n");
            out.write("                                    </li>\r\n");
            out.write("                                    <li>\r\n");
            out.write("                                        <h5>계약면적</h5>\r\n");
            out.write("                                        <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type.acontractSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("㎡</p>\r\n");
            out.write("                                    </li>\r\n");
            out.write("                                </ul>\r\n");
            out.write("                               </div>\r\n");
            out.write("                          </div>\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_app_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_app_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_app_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_app_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_app_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_app_005fforEach_005f1);
      _jspx_th_app_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_app_005fforEach_005f1_reused);
    }
    return false;
  }
}
