/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-10-26 06:31:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Date;

public final class admin_005fship_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Date today = new Date();
DateFormat df = new SimpleDateFormat("yyyyMMddhms");
String dates = df.format(today);

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/admin_css.css?v=");
      out.print(dates);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\">\r\n");
      out.write("<title>관리자 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <form id=\"admin_reg\" name=\"\" method=\"post\" action=\"./admin_join.do\">\r\n");
      out.write("        <div class=\"membody\">\r\n");
      out.write("           <div class=\"adtitle\">ADMINISTRATOR MEMBERSHIP</div>\r\n");
      out.write("           <div class=\"memoutline\" >\r\n");
      out.write("              <div class=\"memsel1\">\r\n");
      out.write("                <ul class=\"memu\">\r\n");
      out.write("                    <li class=\"memfont\">소속 및 부서선택</li>\r\n");
      out.write("                    <li class=\"memlisel1\">\r\n");
      out.write("                        <select name=\"aarea\" class=\"kosel\">\r\n");
      out.write("                            <option value=\"\">소속선택</option>\r\n");
      out.write("                            <option value=\"본사\">본사</option>\r\n");
      out.write("                            <option value=\"경기도\">경기도</option>\r\n");
      out.write("                            <option value=\"인천\">인천</option>\r\n");
      out.write("                            <option value=\"대전\">대전</option>\r\n");
      out.write("                            <option value=\"세종\">세종</option>\r\n");
      out.write("                            <option value=\"광주\">광주</option>\r\n");
      out.write("                            <option value=\"대구\">대구</option>\r\n");
      out.write("                            <option value=\"울산\">울산</option>\r\n");
      out.write("                            <option value=\"전라남도\">전라남도</option>\r\n");
      out.write("                            <option value=\"전라북도\">전라북도</option>\r\n");
      out.write("                            <option value=\"충청남도\">충청남도</option>\r\n");
      out.write("                            <option value=\"충청북도\">충청북도</option>\r\n");
      out.write("                            <option value=\"경상남도\">경상남도</option>\r\n");
      out.write("                            <option value=\"경상북도\">경상북도</option>\r\n");
      out.write("                            <option value=\"제주도\">제주도</option>                            \r\n");
      out.write("                        </select>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul class=\"memu\">\r\n");
      out.write("                    <li class=\"memlisel1\">\r\n");
      out.write("                        <select name=\"adept\" class=\"kosel\">\r\n");
      out.write("                            <option value=\"\">부서선택</option>\r\n");
      out.write("                            <option value=\"임원\">임원</option>\r\n");
      out.write("                            <option value=\"회계팀\">회계팀</option>\r\n");
      out.write("                            <option value=\"영업팀\">영업팀</option>\r\n");
      out.write("                            <option value=\"전산팀\">전산팀</option>\r\n");
      out.write("                            <option value=\"디자인팀\">디자인팀</option>\r\n");
      out.write("                            <option value=\"MD팀\">MD팀</option>\r\n");
      out.write("                            <option value=\"고객관리팀\">고객관리팀</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"memsel1\">\r\n");
      out.write("                <ul class=\"memu\">\r\n");
      out.write("                    <li class=\"memfont\">이름</li>\r\n");
      out.write("                    <li><input type=\"text\" class=\"admamber1\" id=\"\" name=\"aname\" value=\"\" placeholder=\"이름을 입력해 주세요\"></li>\r\n");
      out.write("                    <li class=\"memfont1\">직책</li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <select name=\"aposition\" class=\"kosel\">\r\n");
      out.write("                            <option value=\"임원\">임원</option>\r\n");
      out.write("                            <option value=\"실장\">실장</option>\r\n");
      out.write("                            <option value=\"팀장\">팀장</option>\r\n");
      out.write("                            <option value=\"부장\">부장</option>\r\n");
      out.write("                            <option value=\"차장\">차장</option>\r\n");
      out.write("                            <option value=\"과장\">과장</option>\r\n");
      out.write("                            <option value=\"대리\">대리</option>\r\n");
      out.write("                            <option value=\"주임\">주임</option>\r\n");
      out.write("                            <option value=\"사원\">사원</option>\r\n");
      out.write("                            <option value=\"전체 관리자\">전체 관리자</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("             <div class=\"memsel2\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"memfont\">아이디</li>\r\n");
      out.write("                    <li><input type=\"text\" class=\"admamber2\" id=\"aid\" name=\"aid\" value=\"\" placeholder=\"아이디를 입력해 주세요\"></li>\r\n");
      out.write("                    <li><button class=\"idcheck\" onclick=\"idck(event);\">중복체크</button></li>\r\n");
      out.write("                </ul>    \r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"memsel2\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"memfont\">패스워드</li>\r\n");
      out.write("                    <li><input type=\"password\" class=\"admamber1\" id=\"\" name=\"apw\" value=\"\" placeholder=\"패스워드를 입력해 주세요\"></li>\r\n");
      out.write("                    <li class=\"memfont\">패스워드확인</li>\r\n");
      out.write("                    <li><input type=\"password\" class=\"admamber4\" id=\"\" name=\"apw2\" value=\"\" placeholder=\"동일한 패스워드를 입력해 주세요\"></li>\r\n");
      out.write("                </ul>    \r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"memsel3\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"memfont\">이메일</li>\r\n");
      out.write("                    <li><input type=\"text\" class=\"admamber3\" id=\"\" name=\"aemail\" value=\"\" placeholder=\"이메일을 입력해 주세요\"></li>\r\n");
      out.write("                </ul>    \r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"memsel4\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"memfont\">연락처</li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <select class=\"adnumber\" name=\"atel1\" id=\"\">\r\n");
      out.write("                            <option value=\"010\">010</option>\r\n");
      out.write("                            <option value=\"011\">011</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ad_number\">-</li>\r\n");
      out.write("                    <li><input type=\"text\" class=\"adnumber\" id=\"\" name=\"atel2\" onkeyup=\"tell_value();\" maxlength=\"4\"></li>\r\n");
      out.write("                    <li class=\"ad_number\">-</li>\r\n");
      out.write("                    <li><input type=\"text\" class=\"adnumber\" id=\"\" name=\"atel3\" onkeyup=\"tell_value();\" maxlength=\"4\"></li>\r\n");
      out.write("                    <li><input type=\"hidden\" name=\"atel\" value=\"\"></li>\r\n");
      out.write("                </ul>    \r\n");
      out.write("              </div> \r\n");
      out.write("              \r\n");
      out.write("           </div>\r\n");
      out.write("        </div>\r\n");
      out.write("       <div class=\"admembt\">\r\n");
      out.write("         <ul>\r\n");
      out.write("           <li><button type=\"button\" class=\"admembt_ok\" id=\"adm_ok\" onclick=\"regit();\">신청하기</button></li>\r\n");
      out.write("           <li><button type=\"button\" class=\"admembt_no\" id=\"adm_cancel\" onclick=\"goBack();\">취소하기</button></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("       </div>\r\n");
      out.write("    </form> \r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"../js/adm_btn.js?v=");
      out.print(dates);
      out.write("\"></script>\r\n");
      out.write("<script src=\"../js/admin_ship.js?v=");
      out.print(dates);
      out.write("\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
