/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-10-21 10:21:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import portfolio.FaQdto;
import java.util.List;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class faq_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/admin/view/./ad_menu.jsp", Long.valueOf(1697633106000L));
    _jspx_dependants.put("/admin/view/./ad_copy.jsp", Long.valueOf(1696493190000L));
    _jspx_dependants.put("jar:file:/D:/portfolio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portfolio/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/portfolio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portfolio/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696946006000L));
    _jspx_dependants.put("/admin/view/./fq_main.jsp", Long.valueOf(1697720546000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("portfolio.FaQdto");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

Date aady = new Date();
DateFormat ad = new SimpleDateFormat("yyyyMMddhms");
String add = ad.format(aady);

      out.write("        \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/page_default.css?v=");
      out.print(add);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/admin_css.css?v=");
      out.print(add);
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\">\r\n");
      out.write("<!-- 신규추가된 css 파일 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/notice.css?v=");
      out.print(add);
      out.write("\">\r\n");
      out.write("<!-- 신규추가된 css 파일 끝-->\r\n");
      out.write("<title>관리자 페이지</title>\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

String id =(String) session.getAttribute("name");

      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("<div class=\"menusize\">\r\n");
      out.write("    <ul id=\"menus\">\r\n");
      out.write("        <li class=\"topmenu1\">ADMINISTRATOR</li>\r\n");
      out.write("        <li class=\"topmenu2\"><a href=\"./info_main.do\">환경설정</a></li>\r\n");
      out.write("        <li class=\"topmenu2\"><a href=\"./member_main.do\">회원관리</a></li>\r\n");
      out.write("        <li class=\"topmenu2\"><a href=\"./notice_main.do\">공지사항 관리</a></li>\r\n");
      out.write("        <li class=\"topmenu2\"><a href=\"./faq_main.do\">FAQ</a></li>\r\n");
      out.write("        <li class=\"topmenu2\"><a href=\"./reserve_main.do\">예약현황</a></li>\r\n");
      out.write("        <li class=\"topmenu2\"><a href=\"./config_main.do\">관리자현황</a></li>\r\n");
      out.write("        <li class=\"topmenu3\">");
      out.print(id);
      out.write("님 환영합니다  <a href=\"./logout.do\">[로그아웃]</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write(" </div>\r\n");
      out.write("<div class=\"menuline\"></div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- FAQ 리스트 시작 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Date dday = new Date();
DateFormat as = new SimpleDateFormat("yyyyMMddhms");
String dsa = as.format(dday);

List<FaQdto> fdto = (List<FaQdto>)request.getAttribute("fdto");
int total = (int)request.getAttribute("total");

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!-- FAQ 리스트 시작 -->\r\n");
      out.write("<main class=\"page_main\">\r\n");
      out.write("<section class=\"page_section\">\r\n");
      out.write("<div class=\"listbody\">\r\n");
      out.write("    <div class=\"protitle\">FAQ 관리</div>\r\n");
      out.write("    <div class=\"procho\">\r\n");
      out.write("	   <form id=\"searchForm\" method=\"post\" action=\"./faq_main.do\">\r\n");
      out.write("	       <section class=\"search_part\">\r\n");
      out.write("	        <ol>\r\n");
      out.write("	        <li>FAQ내용 검색</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	        <input type=\"text\" class=\"search_input\" id=\"searchVal\" name=\"searchVal\">\r\n");
      out.write("	        <input type=\"button\" value=\"검색\" class=\"datebtn\" id=\"searchBtn\">\r\n");
      out.write("	        </li>        \r\n");
      out.write("	        <li></li>\r\n");
      out.write("	        <li></li> \r\n");
      out.write("	        </ol>\r\n");
      out.write("       </section> \r\n");
      out.write("	   </form>\r\n");
      out.write("       <section class=\"data_listsview2\">\r\n");
      out.write("       <ul>\r\n");
      out.write("        <li>QA</li>\r\n");
      out.write("        <li>질문/답변</li>\r\n");
      out.write("        <li>글쓴이</li>\r\n");
      out.write("        <li>등록일</li>\r\n");
      out.write("        <li>삭제</li>\r\n");
      out.write("       </ul>\r\n");
      out.write("          \r\n");
      out.write("<!-- FAQ 샘플 HTML 코드 시작 -->           \r\n");
      out.write("     <span id=\"faq_span\">\r\n");
      out.write("     \r\n");
      out.write("     ");
      if (_jspx_meth_app_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     </span>\r\n");
      out.write("<!-- FAQ 샘플 HTML 코드 끝 -->\r\n");
      out.write("       ");
      if (_jspx_meth_app_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       <span class=\"notice_btns\">\r\n");
      out.write("       <input type=\"button\" value=\"FAQ 등록\" onclick=\"regit_faq()\" class=\"meno_btn2\"></span>\r\n");
      out.write("       <aside>\r\n");
      out.write("        <div class=\"page_number\">\r\n");
      out.write("        ");

        int pg = (int) Math.ceil(total/10f);
        
      out.write("\r\n");
      out.write("           <ul>\r\n");
      out.write("           ");
      //  app:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_app_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_app_005fset_005f0_reused = false;
      try {
        _jspx_th_app_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_app_005fset_005f0.setParent(null);
        // /admin/view/./fq_main.jsp(80,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_app_005fset_005f0.setVar("pg");
        // /admin/view/./fq_main.jsp(80,11) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_app_005fset_005f0.setValue(pg );
        int _jspx_eval_app_005fset_005f0 = _jspx_th_app_005fset_005f0.doStartTag();
        if (_jspx_th_app_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_app_005fset_005f0);
        _jspx_th_app_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_app_005fset_005f0_reused);
      }
      out.write("\r\n");
      out.write("           ");
      if (_jspx_meth_app_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("           \r\n");
      out.write("           ");
      if (_jspx_meth_app_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("           </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("       </aside>\r\n");
      out.write("       </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</div> \r\n");
      out.write("</section>\r\n");
      out.write("</main>\r\n");
      out.write("<!-- FAQ 리스트 끝 -->\r\n");
      out.write("<script src=\"../js/fq_main.js?v=");
      out.print(dsa);
      out.write("\"></script>");
      out.write("\r\n");
      out.write("<!-- FAQ 리스트 끝 -->\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("<div class=\"menusize\">Copyright ⓒ 2023 Raemian 분양안내 관리 시스템 All rights reserved</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_app_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_app_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_app_005fforEach_005f0_reused = false;
    try {
      _jspx_th_app_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_app_005fforEach_005f0.setParent(null);
      // /admin/view/./fq_main.jsp(49,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f0.setVar("item");
      // /admin/view/./fq_main.jsp(49,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin/view/./fq_main.jsp(49,5) '${fdto}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${fdto}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_app_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_app_005fforEach_005f0 = _jspx_th_app_005fforEach_005f0.doStartTag();
        if (_jspx_eval_app_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("       <ul class=\"node ques\">\r\n");
            out.write("        <li>Q</li>\r\n");
            out.write("        <li style=\"text-align: left; justify-content: flex-start;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.getFquestion()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("        <li>관리자</li>\r\n");
            out.write("        <li>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.getFindate().substring(0,10)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("        <li>\r\n");
            out.write("        <input type=\"button\" value=\"삭제\" class=\"delbtn\" id=\"delBtn");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.getFidx()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" onclick=\"del_faq(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.getFidx()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">\r\n");
            out.write("        </li>\r\n");
            out.write("       </ul>\r\n");
            out.write("      <!-- display:none 또는 display:flex 로 해야합니다. -->\r\n");
            out.write("       <ol class=\"answer\" style=\"display: none;\">\r\n");
            out.write("        <li>A</li>\r\n");
            out.write("        <li style=\"text-align: left; justify-content: flex-start;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.getFanswer()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("       </ol> \r\n");
            out.write("       ");
            int evalDoAfterBody = _jspx_th_app_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_app_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_app_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_app_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_app_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_app_005fforEach_005f0);
      _jspx_th_app_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_app_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_app_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_app_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_app_005fif_005f0_reused = false;
    try {
      _jspx_th_app_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_app_005fif_005f0.setParent(null);
      // /admin/view/./fq_main.jsp(67,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty fdto}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_app_005fif_005f0 = _jspx_th_app_005fif_005f0.doStartTag();
      if (_jspx_eval_app_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	       <ul class=\"nodatas\">\r\n");
          out.write("	        <li>등록된 FAQ 내용 없습니다.</li>\r\n");
          out.write("	       </ul>\r\n");
          out.write("       ");
          int evalDoAfterBody = _jspx_th_app_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_app_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest.reuse(_jspx_th_app_005fif_005f0);
      _jspx_th_app_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_app_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_app_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_app_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_app_005fset_005f1_reused = false;
    try {
      _jspx_th_app_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_app_005fset_005f1.setParent(null);
      // /admin/view/./fq_main.jsp(81,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fset_005f1.setVar("ww");
      // /admin/view/./fq_main.jsp(81,11) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_app_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/admin/view/./fq_main.jsp(81,11) '1'",_jsp_getExpressionFactory().createValueExpression("1",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_app_005fset_005f1 = _jspx_th_app_005fset_005f1.doStartTag();
      if (_jspx_th_app_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_app_005fset_005f1);
      _jspx_th_app_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_app_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_app_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_app_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_app_005fforEach_005f1_reused = false;
    try {
      _jspx_th_app_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_app_005fforEach_005f1.setParent(null);
      // /admin/view/./fq_main.jsp(83,11) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f1.setBegin(1);
      // /admin/view/./fq_main.jsp(83,11) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pg}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /admin/view/./fq_main.jsp(83,11) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f1.setStep(1);
      // /admin/view/./fq_main.jsp(83,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f1.setVar("ww");
      int[] _jspx_push_body_count_app_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_app_005fforEach_005f1 = _jspx_th_app_005fforEach_005f1.doStartTag();
        if (_jspx_eval_app_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("           <li onclick=\"movePage(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ww}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\"><a href=\"./faq_main.do?fidx=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ww}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ww}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("           ");
            int evalDoAfterBody = _jspx_th_app_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_app_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_app_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_app_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_app_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_app_005fforEach_005f1);
      _jspx_th_app_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_app_005fforEach_005f1_reused);
    }
    return false;
  }
}
